[package]
edition = "2021"
name = "zpass"
version = "0.1.0"

[dependencies]
chrono = {version = "0.4.38", features = ["serde"]}
console = "0.15.8"
dialoguer = "0.11.0"
serde = {version = "1.0.204", features = ["derive"]}
serde_json = "1.0.120"
